### ISSUE TITLE
Datensätze mit Maßeinheit.

### ISSUE THREAD

**Issue by animatorecmd** [bluerai/ioBroker.mobile-alerts#10]

**Comment by animatorecmd** [comment]
Entschuldigung wenn ich das Thema nochmal aufwärmen muss, es gab in der letzten Zeit nicht so viel Regen für eine Kontrolle. Aber beim Regen sind die mm derzeit verschwunden. Datür sind bei Boe und Windgeschwindigkeit noch die Km/h.

Würde dir gern meine ID der Wetterstation zum testen geben, kannst du mir eine PN schreiben?

**Comment by bluerai** [comment]
Jetzt werden auch die km/h entfernt. Gibt es weitere Einheiten? Jede zu entfernende Einheit wird im Code angegeben.
Ich weiß, das ist nicht sehr elegant, aber ich habe zurzeit nicht genügend Zeit, das zu ändern.

**Comment by animatorecmd** [comment]
Perfekt, alles getestet.

Bei mir sind jetzt alle Datensätze ohne Maßeinheit.

Vielen Dank für die Mühen.

**Comment by bluerai** [comment]
ok, danke für die Rückmeldung. Ich schließe den Fall. R.
