### ISSUE TITLE
Kontaktsensoren von TFA Dostmann

### ISSUE THREAD

**Issue by dg1bor** [bluerai/ioBroker.mobile-alerts#11]
Moin, habe mehrere TFA Dostmann Kontaktsensoren MA 30.3311.02 an meinen Türen und Fenstern und möchte mit dem Adapter mobile-alerts diese zeitnah(Sofort)  für Skripte nutzen:

![image](https://user-images.githubusercontent.com/19173567/106868083-9f7d0980-66ce-11eb-80dd-9f096087f70e.png)

Beispiel - Lüftung max. 10 min - Öffnen des Kontaktes löst Timer aus und Google Home meldet wenn Zeitpunkt erreicht.
Dazu habe ich einen Skript geschrieben.  Dieser funktioniet mit anderen Schaltern (Zigbee - Lidl Bewegungsmelder) sofort aber leider nicht mit den Schließkontakten. Die Kontakte werden  in den Objekten unter mobile-alerts auch angezeigt. Status und Zeitpunkt ebenso, aber leider erst nach gefüllten Stunden.
Läst sich das Abfrageintervall  irgendwie verändern ?

Gruß
Gerrybauer

**Comment by bluerai** [comment]
Hi, unter Instanzen --> Zeitplanung kann das Abfrageintervall eingestellt werden. Ein sehr kurzes Intervall belastet natürlich den ioBroker-Server. Möglicherweise sollten die Abfragen für diese Anforderung besser eventgesteuert getriggert werden. Das geht aber (zurzeit) nicht mit diesem Mobile-Alerts-Adapter. Gruß bluerai
