### ISSUE TITLE
Adapter does not provide values any more

### ISSUE THREAD

**Issue by MichaelSchaaf999** [bluerai/ioBroker.mobile-alerts#12]
Since "Umstellung der Request-Methode auf Post Stand: 15.04.2021": No up to date values in the objects.
Log says: 

host.iobroker | 2021-04-15 07:17:00.555 | error | instance system.adapter.mobile-alerts.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
mobile-alerts.0 | 2021-04-15 07:17:00.544 | error | (15641) Termination forced due to timeout!
mobile-alerts.0 | 2021-04-15 07:14:00.736 | error | (15641) **No valid response from Mobile Alerts server**

What do we have to do to keep on getting the values?

**Comment by bluerai** [comment]
Hi, no error on my iobroker instance. Please run adapter in debug mode and send me the log. Rai

**Comment by MichaelSchaaf999** [comment]
Thanks Rai,
how would I have to proceed to run the adapter in debug mode? Never done that before.
Thx
Michael

p.s.: 
 | error | (15823) No valid response from Mobile Alerts server. -- | -- | --

**Comment by bluerai** [comment]
>> Tab "Instances". Set "Expert mode" (icon "Man with tool"). Set "Log level" for mobile-alerts to "debug".

**Comment by MichaelSchaaf999** [comment]
Thanks, done that.
This is the download file of the log - is that what you meant?


mobile-alerts.0 | 2021-04-15 07:52:00.688 | error | (16181) No valid response from Mobile Alerts server
-- | -- | -- | --
mobile-alerts.0 | 2021-04-15 07:52:00.508 | debug | (16181) out: main
mobile-alerts.0 | 2021-04-15 07:52:00.505 | debug | (16181) https://measurements.mobile-alerts.eu/Home/SensorsOverview?phoneid=549301590686
mobile-alerts.0 | 2021-04-15 07:52:00.504 | debug | (16181) in: main v1.02
mobile-alerts.0 | 2021-04-15 07:52:00.495 | info | (16181) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.mobile-alerts, node: v12.22.1, js-controller: 3.2.16
mobile-alerts.0 | 2021-04-15 07:48:50.969 | debug | (16125) system.adapter.admin.0: logging true
mobile-alerts.0 | 2021-04-15 07:48:06.154 | debug | (16125) system.adapter.admin.0: logging false
mobile-alerts.0 | 2021-04-15 07:48:00.705 | error | (16125) No valid response from Mobile Alerts server
mobile-alerts.0 | 2021-04-15 07:48:00.524 | debug | (16125) out: main
mobile-alerts.0 | 2021-04-15 07:48:00.521 | debug | (16125) https://measurements.mobile-alerts.eu/Home/SensorsOverview?phoneid=549301590686
mobile-alerts.0 | 2021-04-15 07:48:00.521 | debug | (16125) in: main v1.02
mobile-alerts.0 | 2021-04-15 07:48:00.512 | info | (16125) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.mobile-alerts, node: v12.22.1, js-controller: 3.2.16
mobile-alerts.0 | 2021-04-15 07:48:00.400 | debug | (16125) statesDB connected
mobile-alerts.0 | 2021-04-15 07:48:00.400 | debug | (16125) States connected to redis: 127.0.0.1:9000
mobile-alerts.0 | 2021-04-15 07:48:00.354 | debug | (16125) States create User PubSub Client
mobile-alerts.0 | 2021-04-15 07:48:00.354 | debug | (16125) States create System PubSub Client
mobile-alerts.0 | 2021-04-15 07:48:00.350 | debug | (16125) Redis States: Use Redis connection: 127.0.0.1:9000
mobile-alerts.0 | 2021-04-15 07:48:00.350 | debug | (16125) objectDB connected
mobile-alerts.0 | 2021-04-15 07:48:00.347 | debug | (16125) Objects connected to redis: 127.0.0.1:9001
mobile-alerts.0 | 2021-04-15 07:48:00.337 | debug | (16125) Objects client initialize lua scripts
mobile-alerts.0 | 2021-04-15 07:48:00.337 | debug | (16125) Objects create User PubSub Client
mobile-alerts.0 | 2021-04-15 07:48:00.336 | debug | (16125) Objects create System PubSub Client
mobile-alerts.0 | 2021-04-15 07:48:00.336 | debug | (16125) Objects client ready ... initialize now
mobile-alerts.0 | 2021-04-15 07:48:00.323 | debug | (16125) Redis Objects: Use Redis connection: 127.0.0.1:9001
mobile-alerts.0 | 2021-04-15 07:45:00.489 | error | (16028) Termination forced due to timeout!

**Comment by bluerai** [comment]
Sorry, but your adapter is not updated to current version. Please update (= same as "installation").

**Comment by MichaelSchaaf999** [comment]
Yes, I will do that.
But there is no alert in the IOBroker adapter summary?
![Uploading grafik.png…]()

So: Updating manually? Not via IOBroker?

**Comment by bluerai** [comment]
Yes, you have to update manually. I did not implement the new ioBroker standards yet.

**Comment by MichaelSchaaf999** [comment]
Throws an error:
<img width="730" alt="grafik" src="https://user-images.githubusercontent.com/53481090/114822303-24b52680-9dc2-11eb-91bd-8c10a77b7fad.png">

...
My fault: I have to take the whole command line you show in the installation proc.

**Comment by MichaelSchaaf999** [comment]
Thanks, bluerai,
working now - excellent service  (well: manual installation is possible but getting such an update alert via IOBroker would be nice to have).
Have a nice day & stay healthy
Michael

**Comment by bluerai** [comment]
Thank you. I'm closing the issue now.
