### ISSUE TITLE
Rain sensor

### ISSUE THREAD

**Issue by Robbsy** [bluerai/ioBroker.mobile-alerts#15]
Possibility to display the values ​​of the rain sensor in rain / hour or other evaluation as in the app

Möglichkeit die Werte des Regensensors in Regen / Stunde oder andere Auswertung wie in der App darzustellen

**Comment by bluerai** [comment]
Sorry, the used messuring units are still hard coded.    :-(
So please tell me the exact unit shown on the Mobile Alerts website. I will put this into the code.

**Comment by Robbsy** [comment]
Hello!

 

The Link for the sensor:

https://measurements.mobile-alerts.eu/Home/MeasurementDetails?deviceid=0877D2D572E2 <https://measurements.mobile-alerts.eu/Home/MeasurementDetails?deviceid=0877D2D572E2&vendorid=0fc72d93-9600-4981-8f9e-0042a726dd1b&appbundle=eu.mobile_alerts.mobilealerts> &vendorid=0fc72d93-9600-4981-8f9e-0042a726dd1b&appbundle=eu.mobile_alerts.mobilealerts

 

My Phone ID if needed: 695694388445

 

Windows shows me the rain in mm like on the csv attached.

Android shows me (calculated?) totals. (see the pics).

 

Thank you for your time!

 

Br

Robert

 

 

 

 

 

Von: bluerai ***@***.***> 
Gesendet: Donnerstag, 13. Mai 2021 16:57
An: bluerai/ioBroker.mobile-alerts ***@***.***>
Cc: Robbsy ***@***.***>; Author ***@***.***>
Betreff: Re: [bluerai/ioBroker.mobile-alerts] Rain sensor (#15)

 

Sorry, the used messuring units are still hard coded. :-(
So please tell me the exact unit shown on the Mobile Alerts website. I will put this into the code.

**Comment by bluerai** [comment]
Oh, the unit is mm. "mm" is already in the code. So the adapter will put the value into the according Mobile Alerts object. That's all the adapter is build for. It's working fine as I see in the linked list.
If you want to make some calculation with this value you have to do it on your own (using the JavaScript adapter) or maybe you can use the History adapter to calculate the mm rain which are fallen in the last hour. 
Sorry, I can give you no further help on this issue because I do not have the rain sensor.

**Comment by Robbsy** [comment]
Thank you!

 

Von: bluerai ***@***.***> 
Gesendet: Donnerstag, 13. Mai 2021 17:53
An: bluerai/ioBroker.mobile-alerts ***@***.***>
Cc: Robbsy ***@***.***>; Author ***@***.***>
Betreff: Re: [bluerai/ioBroker.mobile-alerts] Rain sensor (#15)

 

Oh, the unit is mm. "mm" is already in the code. So the adapter will put the value into the according Mobile Alerts object. That's all the adapter is build for. It's working fine as I see in the linked list.
If you want to make some calculation with this value you have to do it on your own (using the JavaScript adapter) or maybe you can use the History adapter to calculate the mm rain which are fallen in the last hour.
Sorry, I can give you no further help on this issue because I do not have the rain sensor.
