### ISSUE TITLE
Keine Verbindung wegen abgelaufenem Zertifikat

### ISSUE THREAD

**Issue by fisch336** [bluerai/ioBroker.mobile-alerts#23]
Hallo seit gestern Abend diese Meldung:
![2022-10-08 08_41_23-logs - iobroker – Mozilla Firefox](https://user-images.githubusercontent.com/5837818/194693804-3c4659a8-466b-46d0-bf26-d6d3346cd212.jpg)

**Comment by bluerai** [comment]
Hi, ja, das ServerZertifikat des Mobile Alerts Servers ist obsolete. Wir können erstmal nur auf die Aktualisierung durch den Betreiber warten. Gruß bluerai

**Comment by fisch336** [comment]
Ich habe sie mal angeschrieben, vielleicht geht es dann schneller mit dem Fix.

**Comment by ManitheHobbit** [comment]
Hallo. Scheint so als läuft es wieder. Danke

**Comment by fisch336** [comment]
Ja bei mir läuft es auch. Sie haben das Zertifikat erneuert.

![grafik](https://user-images.githubusercontent.com/5837818/194760878-a84c1e34-8353-49da-86c9-bf2c2da4412d.png)

**Comment by peterinpejani** [comment]
Danke! Läuft bei mir auch wieder

⁣TypeApp for Android herunterladen ​

Am 9. Okt. 2022, 15:57, um 15:57, fisch336 ***@***.***> schrieb:
>Closed #23 as completed.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bluerai/ioBroker.mobile-alerts/issues/23#event-7549440021
>You are receiving this because you are subscribed to this thread.
>
>Message ID:
***@***.***>
