### ISSUE TITLE
Nicht alle Daten werden in die IOBroker-DB geschrieben

### ISSUE THREAD

**Issue by NoPlayBack** [bluerai/ioBroker.mobile-alerts#24]
Bin neuer Benutzer von IOBroker und mobile-alerts.
Der Adapter läuft bei mir mit einer Instanz, und ich sehe alle Messwerte als Objekte. In der Objekte-View in IOBroker sehe ich auch gültige und aktuelle Daten.
Die Daten sollen alle per SQL-Protokollierung in die DB geschrieben werden. Das funktioniert jedoch nicht mit allen Werten. Es fehlen alle drei Daten vom Windmesser MA 10660 (Windgeschwindigkeit, Böe, Windrichtung) und eines von drei Daten vom Luftdruckmonitor MA 10238 (Luftdruck fehlt, Temp und Feuchte ist vorhanden).
Wie gesagt, in der Objekte-View sind die Daten zu sehen.
Irgendeine Idee woran das liegen könnte?

Update 01: habe gerade in den Protokollen von iobroker etwas gefunden:
sql.0 | 2022-10-30 11:14:26.857 | info | Do not store value "0,8 m/s" for Garagendach.Boee because no number
sql.0 | 2022-10-30 11:14:26.855 | info | Do not store value "0,2 m/s" for Garagendach.Windgeschwindigkeit because no number
sql.0 | 2022-10-30 11:14:26.850 | info | Do not store value "1018,9 hPa" for Dachstuhl.Luftdruck because no number
Windrichtung ist in der DB für Zeichenketten gelandet.
Der Grund scheint wohl zu sein dass die Einheiten nicht entfernt werden, die wären hier "m/s" und "hPa".
Das ist ja auch so in den Settings von der Instanz zu lesen:
"Falls ausgewählt, wird der reine Zahlenwert gespeichert (nützlich wenn weitere Berechnungen erfolgen sollen).
Nur für Temperaturen in °C and °F, Prozentwerte (%), Längen in mm and Geschwindigkeiten in km/h"

Gibt es eine Chance das zu implementieren???

Update 02:
Ist jetzt ein Monolog geworden, aber ich habe gerade eine Änderung gemacht die für mich die Lösung ist... mit der Bitte um Implementierung in einer der nächsten Versionen, falls diese Änderung für gut befunden wird:
in main.js muss eine Zeile geändert werden, in der Function formatNum(s):
			var patternNumber = /^(-|\+)?\d+(,|\.)?\d* *(C|F|%|mm|hPa|m\/s|km\/h)$/;
Dann wird auch bei m/s und hPa der reine Zahlenwert erzeugt, und findet damit auch seinen Weg in die DB für die Zahlen.
Die main.js finde ich bei mir auf dem Raspberry in /opt/iobroker/node_modules/iobroker.mobile-alerts

**Comment by KLIS-IT** [comment]
Moin @NoPlayBack 

Ich habe mal deinen Change eingefügt und einen PR erstellt.
Mal sehen, ob das so durch geht.

Viele Grüße
Karsten

**Comment by NoPlayBack** [comment]
Super, vielen Dank.

Ich kenne mich mit Internas von Github leider gar nicht aus, daher freue ich mich sehr dass du dort mein Thema in die richtigen Bahnen gelenkt hast 😉

 

Grüße

Eddie

 

Von: KLIS-IT ***@***.***> 
Gesendet: Montag, 31. Oktober 2022 08:32
An: bluerai/ioBroker.mobile-alerts ***@***.***>
Cc: NoPlayBack ***@***.***>; Mention ***@***.***>
Betreff: Re: [bluerai/ioBroker.mobile-alerts] Nicht alle Daten werden in die IOBroker-DB geschrieben (Issue #24)

 

Moin @NoPlayBack <https://github.com/NoPlayBack> 

Ich habe mal deinen Change eingefügt und einen PR erstellt.
Mal sehen, ob das so durch geht.

Viele Grüße
Karsten

**Comment by KLIS-IT** [comment]
@bluerai 
Was muss man denn noch machen, um nach dem PR ein Release 0.5.2 zu erstellen, das dann im ioBroker verfügbar ist?

Viele Grüße
Karsten

**Comment by bluerai** [comment]
Ok, neues Release erstellt! bluerai
