### ISSUE TITLE
Daten werden nicht mehr abgerufen

### ISSUE THREAD

**Issue by MichaelSchaaf999** [bluerai/ioBroker.mobile-alerts#26]
Log:

mobile-alerts.0 | 2023-01-17 18:42:00.809 | error | Cannot read property 'statusCode' of undefined
-- | -- | -- | --
mobile-alerts.0 | 2023-01-17 18:42:00.809 | error | TypeError: Cannot read property 'statusCode' of undefined at Request._callback (/opt/iobroker/node_modules/iobroker.mobile-alerts/main.js:97:59) at self.callback (/opt/iobroker/node_modules/iobroker.mobile-alerts/node_modules/request/request.js:186:22) at Request.emit (events.js:400:28) at Request.onRequestError (/opt/iobroker/node_modules/iobroker.mobile-alerts/node_modules/request/request.js:878:8) at ClientRequest.emit (events.js:400:28) at TLSSocket.socketErrorListener (_http_client.js:475:9) at TLSSocket.emit (events.js:400:28) at emitErrorNT (internal/streams/destroy.js:106:8) at emitErrorCloseNT (internal/streams/destroy.js:74:3) at processTicksAndRejections (internal/process/task_queues.js:82:21)
mobile-alerts.0 | 2023-01-17 18:42:00.808 | error | uncaught exception: Cannot read property 'statusCode' of undefined
host.iobroker | 2023-01-17 18:39:54.062 | error | Invalid request getRepository. "callback" or "from" is null
host.iobroker | 2023-01-17 18:35:01.412 | error | instance system.adapter.mobile-alerts.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
mobile-alerts.0 | 2023-01-17 18:35:00.897 | error | Cannot read property 'statusCode' of undefined
mobile-alerts.0 | 2023-01-17 18:35:00.897 | error | TypeError: Cannot read property 'statusCode' of undefined at Request._callback (/opt/iobroker/node_modules/iobroker.mobile-alerts/main.js:97:59) at self.callback (/opt/iobroker/node_modules/iobroker.mobile-alerts/node_modules/request/request.js:186:22) at Request.emit (events.js:400:28) at Request.onRequestError (/opt/iobroker/node_modules/iobroker.mobile-alerts/node_modules/request/request.js:878:8) at ClientRequest.emit (events.js:400:28) at TLSSocket.socketErrorListener (_http_client.js:475:9) at TLSSocket.emit (events.js:400:28) at emitErrorNT (internal/streams/destroy.js:106:8) at emitErrorCloseNT (internal/streams/destroy.js:74:3) at processTicksAndRejections (internal/process/task_queues.js:82:21)
mobile-alerts.0 | 2023-01-17 18:35:00.896 | error | uncaught exception: Cannot read property 'statusCode' of undefined

host.iobroker | 2023-01-17 18:42:01.321 | error | instance system.adapter.mobile-alerts.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --

Was kann ich tun?

LG
M

**Comment by bluerai** [comment]
Hallo Michael,
ja, da können wir zunächst gar nichts tun. Die Mobile-Alerts-Übersichtseite, die in diesem Adapter zum Auslesen der Daten verwendet wurde, gibt es nicht offenbar mehr. ... war ja auch eher eine Krücke aus der Zeit als MA nichts anderes zur Verfügung gestellt hat.
Wir benötigen einen anderen, ggf. neu zu entwickelnden Adapter - am besten einen, der über die MA REST-API zugreift. 
Hinweis: Anstelle der alten Übersichtsseite gibt es eine Monitoring-Seite von MA unter https://monitor.mobile-alerts.eu
Gruß Raiblue

**Comment by MichaelSchaaf999** [comment]
Hi, nAbend,
da haben sie ja anscheinend gestern oder heute schlagartig was geändert, natürlich ohne die Kunden zu informieren.
Monitoring-Seite: Wie komme ich denn in der auf "mein" Profil?
Wenn ich da einen account anlege, kann ich nicht mal Devices hinzufügen.

LG 
M

**Comment by bluerai** [comment]
Hallo Michael,
Devices werden über den Button "Sender hinzufügen" angelegt. Ein Testdevice ist bereits angelegt. Habe einen Temperatursensor eingefügt ... ist soweit ok. Sieht etwa so wie in der Mobile-App aus.
Klappt aber nicht für alle MA-Geräte. Zum Beispiel die Wetterstation MA10410 wird nicht unterstützt. 
Gruß Raiblue

**Comment by MichaelSchaaf999** [comment]
stinknormale MA10230
![image](https://user-images.githubusercontent.com/53481090/213103734-b192f897-bfa2-48ff-9db6-4e7baa292a93.png)
...werden dann aber als "nicht unterstützt" abgewiesen??!?
<img width="517" alt="image" src="https://user-images.githubusercontent.com/53481090/213103990-25119a94-9fe4-4f64-b777-e9947bf9ff37.png">

Da kannst DU natürlich nichts für. Aber was für ein Service ist das denn?
Nun: Ich hab mal Tickets aufgemacht, mal schauen, was da heute als Antwort kommt, wenn überhaupt.

**Comment by KLIS-IT** [comment]
Seit heute (2023-01-18) um etwa 9 Uhr ist die Seite https://measurements.mobile-alerts.eu/ wieder erreichbar und aktiv.

**Comment by bluerai** [comment]
@KLIS-IT Danke für die Info!

Da geht es also doch noch weiter! Trotz alledem sollte man sich Gedanken über einen Umbau des Adapters in Richtung Integration der offiziellen REST-API machen ...

**Comment by MichaelSchaaf999** [comment]
Auch ich kann bestätigen: Geht wieder. Vermutlich war nur ihr Server offline oder sowas.
