### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by Ball-Pic** [bluerai/ioBroker.mobile-alerts#27]
The installation does not complete without error or warnings:
Does this affect the functionality?

Here is the log:

$ iobroker url https://github.com/bluerai/ioBroker.mobile-alerts.git --host iobroker --debug

install bluerai/ioBroker.mobile-alerts#558b1275accf47ce5f58073481a8af6e57bfa390

NPM version: 6.14.17

Installing bluerai/ioBroker.mobile-alerts#558b1275accf47ce5f58073481a8af6e57bfa390... (System call)

npm WARN deprecated har-validator@5.0.3: this library is no longer supported

npm WARN deprecated hawk@6.0.2: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.

npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN http-cookie-agent@4.0.2 requires a peer of tough-cookie@^4.0.0 but none is installed. You must install peer dependencies yourself.npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})+ iobroker.mobile-alerts@0.5.1added 19 packages from 31 contributors in 869.121s

upload [0] mobile-alerts.admin /opt/iobroker/node_modules/iobroker.mobile-alerts/admin/mobile-alerts.png mobile-alerts.png image/png

Process exited with code 0

**Comment by bluerai** [comment]
HI, should be no problem for now. I 'm away, I will update the dependencies  after return. Best regards, bluerai
