### ISSUE TITLE
Exchange of a sensor, now the sensor is not logged any more

### ISSUE THREAD

**Issue by NoPlayBack** [bluerai/ioBroker.mobile-alerts#28]
I did have a broken sensor so i needed to buy a new one of same type.
The mobile-alerts-is is now a different one.
What i did:
- Did rename the old sensor in the mobile-alerts-app on my phone to something different
- Have paired the new sensor with the mobile-alerts-app and renamed it to the same as the old sensor was
- After some time i did go into IOBroker and did see the new sensor id listed in objects.
- did activate logging on the three datapoints which the sensor sends out... and did set everything the same, also the Alias-ID is the same.
- after that i did get 2 values at almost the same timestamp in iobroker.ts_number: the value from the old sensor (frozen and with old timestamp) and the value with new sensor
- so i did deactivate the logging of the datapoints for the old sensor.

After that step, no data is logged any more from that new sensor.
Immediately after that step i did get warnings in IOBroker saying:
sql.0 | 2023-02-15 14:13:24.269 | warn | getOneCachedData: got null states 1 times for Alias-ID

The data shown on the IOBroker-Objects page is correct !

**Comment by bluerai** [comment]
I don't really understand what logging you 're meaning. If the ioBroker objects are filled with the correct values, then the job of the mobile alerts adapter is completed.

**Comment by NoPlayBack** [comment]
In IOBroker page "Objects" one can select one of the datapoints (like temperature) and on the right side click on the settings (toothwheel).
In that page one can activate the logging of the data into a db, for permanent storage.
And yes, if you are saying that this has nothing to do any more with your module but it is a pure IOBroker feature, then i have to check for solution in that area...

**Comment by bluerai** [comment]
Ok, it's the "history adapter". I think at first you should try to restart the adapter or maybe you need to reinstall it?

**Comment by NoPlayBack** [comment]
That's it.... i did have this adapter installed:
https://github.com/ioBroker/ioBroker.sql
This one enables to store history data into sql-db.
After restarting the instance of that adapter it did immediatly start to log the data.

So yes, not at all a topic for your adapter, it was the sql-adapter having a hickup because of the change of the sensors....
