### ISSUE TITLE
code 1 (JS_CONTROLLER_STOPPED)

### ISSUE THREAD

**Issue by MichaelSchaaf999** [bluerai/ioBroker.mobile-alerts#29]
Hi Rai,
adapter terminating with code 1, no connection, no values provided from the server.
What can we do?
Best
M

**Comment by bluerai** [comment]
Hello Michael, sorry , I don't support this Adapter any more. Please see README.md. With Regards, Rai

**Comment by MichaelSchaaf999** [comment]
Thanks, Rai,
ein völlig unkommentiertes Script, ja. Und die offizielle API-Doku sagt ja auch nix über dies Script aus, kann sie ja nicht.
Jetzt soll ich also, als der direkten Script-Sprache nicht mächtig (ich kann höchstens Blockly) so lange da rumbasteln, bis meine 17 mobile-alerts Devices da alle drin sind und funktionieren und gefüllte Datenpunkte zurückliefern?
Das ist ja irgendwie schon ein Rückschritt. Sorry.
LG 
Michael

**Comment by bluerai** [comment]
Hello, Michael, ich verstehe, dass du die Situation nicht so gut findest. Aber vielleicht kann dir bei dem aktuellen Problem ein anderer User helfen. Ich kann es nicht, da ich den Adapter nicht mehr einsetze.

Kurzer Hinweis zu example.js:
Wenn du "example.js" benutzen möchtest, brauchst du im einfachen Fall (z.B. Temperatursensor) nur den "propertyArray" anzupassen: id + Pfade für die Datenpunkte. Die Bezeichnungen t1, t2, h1,... entsprechen der API-Doku. Falls andere Sensoren als in dem Beispiel auftreten, muss du ein entsprechendes "measurement" analog zu den vorhandenen definieren. Die Inhalte sind dann der API-Doku zu entnehmen.

Gruß Rai

**Comment by MichaelSchaaf999** [comment]
Hi Rai,
nun - vieles könnte man ja abgucken. Aber: Warum finde ich da ""t1", 'hm-rega.0.xxxxx'", wir sind doch eigentlich bei MobileAlerts und nicht bei Homematic? Und wo muss die Phone-ID eingetragen werden? Usw usw.
Also ohne Kommentare in dem Script tu ich mich da schwer.
LG  
M

**Comment by MichaelSchaaf999** [comment]
Hi Rai,
ich glaube, dann schick ich die URL lieber durch den Parser. Dann hab ich weniger Arbeit mit Deinem Script.
LG 
M

**Comment by bluerai** [comment]
Hi, ich habe example.js jetzt so angepasst, dass es direkt verwendet werden kann. Es holt nun. die Daten von einigen Testsensoren nach ioBroker. Ich denke, das hilft für den Start. Gruß Rai

**Comment by MichaelSchaaf999** [comment]
Hi Rai,
das sieht ja nun schon seeeehr viel besser aus. Frage: Wo landen eigentlich die "log('xxxxxx ..."?
LG 
M

**Comment by MichaelSchaaf999** [comment]
Hi Rai,
sehr sehr sehr gut jetzt. Frage noch: Wo finde ich die "log"-Meldungen?
Das Script funktioniert jetzt, nach ein paar Anpassungen, hervorragend. Der alte Adapter ist tatsächlich völlig überflüssig. 
Vielen lieben Dank für die Hilfe!
Vorab ein schönes WoEnde wünscht
M

**Comment by bluerai** [comment]
Hi Michael,
schön, dass das Script für dich nützlich ist!

Es wird ganz normal geloggt, d.h. die Log-Einträge sollten auf jeden Fall im ioBroker-Protokoll (erreichbar über die linke Seitenleiste) zu finden sein. 
Falls in dem Log-Fenster unter dem Script nichts angezeigt wird, wird das Log möglicherweise in das Log-Fenster eines anderen Scripts geleitet. Das liegt dann vielleicht an den Script-Namen. Vermeide so etwas die gleichzeitige Verwendung von z.B. "MobileAlerts" und  "MobileAlertsTest", d.h. der eine Name ist der Beginn des anderen. Dagegen ist z.B. "MobileAlertsProduktion" und  "MobileAlertsTest" ok. (Das scheint ein Fehler im JavaScript-Adapter zu sein.)

Noch eine Frage: Hast du bei deinen Anpassungen ein neues "measurement" erstellt? Wenn du es mir sendest, füge ich es noch in das Example.js ein.

Gruß & schönes WE, Rai

**Comment by MichaelSchaaf999** [comment]
Hi Rai,

- die Log-Einträge finde ich nicht im Protokoll. 
- Mein javascript.0-Adapter hat allerdings als Log-Stufe "error" eingestellt, falls Dein Script da leichtere Stufen als Error verwendet, dann blende ich das vielleicht aus?
- Ein neues Measurement; Du hast 02, 04 und 07 im Beispiel? Ich habe noch 03 benötigt, das ist mit Temperatur, Luftfeuchtigkeit quasi bei uns hier Standard.

const measurement03 =  new Map([["lb", {name: "lowbattery", type: "boolean", unit: ""}], 
    ["t1", {name: "Temperatur", type: "number", unit: "°C"}], 
    ["h", {name: "Luftfeuchte, innen", type: "number", unit: "%"}], 
    ["ts", {name: "Timestamp", type: "number", unit: "sec"}],
    ["lb", {name: "Low Battery", type: "boolean", unit: ""}]]);

Gleichfalls ein schönes WoEnde & liebe Grüße
M

**Comment by bluerai** [comment]
Danke für das "measurement03 " und stell bitte das Log-Level für den JS-Adapter auf "info". Gruß R

**Comment by MichaelSchaaf999** [comment]
Log-Level für JS-Adapter auf "info" gestellt: Da fand ich dann auch die Log-Einträge des Scripts.
Vielen Dank.
Da mir der JS-Adapter aber sonst immer zu "gesprächig" war, hatte ich dort eben auf "Error" gestellt.

**Comment by MichaelSchaaf999** [comment]
p.s.: Kann man den log-Befehl nicht mit einem "Error"-Level versehen?

p.p.s.: GEFUNDEN - der Level wird ja als letzter Parameter im Log-Befehl mitgegeben. Läuft.

Cheers
M

**Comment by MichaelSchaaf999** [comment]
Lieber RAI,

wir benutzen hier ja seit 2023 (?) Dein alternatives Script als Ersatz zum alten, nicht mehr gepflegten mobile-alters-Adapter. Also das Script aus Deinem Folder „alternative“.
Ergänzt um die Devices, die wir hier haben.

Läuft problemlos und ohne Klagen.

Nun wollte ich ein MA10402 hinzufügen, also einen „Luftgütemonitor“.
Nun finde ich eine solche ID leider nicht in der MA-Doku, so daß ich in Deinem Script keine ID für dies Gerät anlegen kann, das ja mindestens einen zusätzlichen Parameter hat: Nämlich den Wert für die Luftgüte.

Hast Du hier bitte einen Tipp, wo man eine solche ID für ein 10402 Device finden kann?
Denn dann könnte ich ja in Dein Script eine „const measurement xx“ anlegen, um mit diesem Script auch die Werte vom Device 10402 holen zu können.
Es geht ja um die Parameter t1, h, ts, lb UND eben um den Wert für die Luftqualität (CO2 äquivalenter Messwert, bspw 850).

Es wäre also sehr hilfreich, wenn Du hier einen Tipp oder einen Link hättest: Denn in der (wohl schon recht alten) MA-Doku "Mobile Alerts REST API“ finde ich hierzu nichts.

Danke im Voraus & liebe Grüße
Michael


Michael Claßen  | fon +49 172  52 33 6 33  | fax +49  7172  30 64 98 4   |  Härtsfeldstr. 1  73553 Alfdorf   | mail: ***@***.***



------ Originalnachricht ------
Von "bluerai" ***@***.******@***.***>>
An "bluerai/ioBroker.mobile-alerts" ***@***.******@***.***>>
Cc "Michael Schaaf" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Datum 16.06.2023 10:59:45
Betreff Re: [bluerai/ioBroker.mobile-alerts] code 1 (JS_CONTROLLER_STOPPED) (Issue #29)


Hi Michael,
schön, dass das Script für dich nützlich ist!

Es wird ganz normal geloggt, d.h. die Log-Einträge sollten auf jeden Fall im ioBroker-Protokoll (erreichbar über die linke Seitenleiste) zu finden sein.
Falls in dem Log-Fenster unter dem Script nichts angezeigt wird, wird das Log möglicherweise in das Log-Fenster eines anderen Scripts geleitet. Das liegt dann vielleicht an den Script-Namen. Vermeide so etwas die gleichzeitige Verwendung von z.B. "MobileAlerts" und "MobileAlertsTest", d.h. der eine Name ist der Beginn des anderen. Dagegen ist z.B. "MobileAlertsProduktion" und "MobileAlertsTest" ok. (Das scheint ein Fehler im JavaScript-Adapter zu sein.)

Noch eine Frage: Hast du bei deinen Anpassungen ein neues "measurement" erstellt? Wenn du es mir sendest, füge ich es noch in das Example.js ein.

Gruß & schönes WE, Rai
