### ISSUE TITLE
Warnmeldung "This object will not be created in future versions" bei Verwendung des alternativen Scripts

### ISSUE THREAD

**Issue by KLIS-IT** [bluerai/ioBroker.mobile-alerts#30]
Hallo @bluerai.

Zuerst einmal viel dank für die Bereitstellung des alternativen Scripts.
Einrichtung und Datenabruf laufen ohne Probleme.

Allerdings wurde bei der ersten Ausführung für jedes Gerät dieser Eintrag im log erzeugt.

This object will not be created in future versions. Please report this to the developer.
Object javascript.0.mobileAlerts.Devices.xxxxxxxxxxxx is invalid: obj.type has to exist

Dies wird immer für das Objekt "Low Battery" (lb) erzeugt, da die Unit "" ist.
Was wäre da ein guter Wert in der Konfig?

Danke + viele Grüße
Karsten

**Comment by bluerai** [comment]
Hi Karsten, ich habe das Script angepasst. Jetzt sollten keine Warnungen mehr auftreten. Gruß Blue Rai

**Comment by KLIS-IT** [comment]
Hi @bluerai 

Vielen Dank - jetzt funktioniert es auch ohne Fehlermeldung.

Danke + viele Grüße
Karsten
