### ISSUE TITLE
Keine Datenübernahme der Mobile.Alerts Sensoren im IOBroker

### ISSUE THREAD

**Issue by dg1bor** [bluerai/ioBroker.mobile-alerts#31]
seit 21.08.23 werden bei mir keine aktuelle Daten mehr von den MA Sensoren übernommen. 
Die APP Daten sind aktuell!
Hab mir auch mal das Java Skript installiert, jedoch wurden zwar unter "Objekte -  javascript" alle Datenpunkte abgelegt aber ohne die Messdaten. Der MA Adapter 0.5.1 ist parallel auch noch aktiv!!

Gruß
Gerhard

**Comment by bluerai** [comment]
Den MA-Adapter unterstütze ich nicht mehr und habe ihn aus meiner iobroker-Umgebung entfernt. Die letzte Version war allerdings 0.5.2.
Das Beispielscript "alternative/example.js" funktioniert bei mir einwandfrei.
Die Datenübernahme von meinen eigenen Sensoren geht ebenfalls ohne Probleme (analog zu example.js).

Verwendest du die letzte Version von example.js? Internetverbindung ok? Firewall?

Gruß bluerai

**Comment by dg1bor** [comment]
Hallo die Datei example.js habe ich heute von Github heruntergeladen. das java gestartet, die Datenpunkte wurden angelegt jedoch nicht mit Werten gefüllt.
Der Java Debug zeigt eine error-meldung  "Receiving Data ended with errorcode undefined(#1, 0sec).

Eine Version 0.5.2 habe wie in der Anleitung handisch installiert. ohne Fehlermeldung
Die AdapterEinstellungen zeigt aber noch die 0.5.1  - alte Werte....

Der ioBroker läuft auf einer ProxMox Instanz

Gruß
Gerhard

**Comment by bluerai** [comment]
Zwei Hinweise:

1. Ich habe noch ein paar kleine Änderungen an dem example.js-Script hochgeladen.

2. Ist auf deinem Server überhaupt cron installiert? 

Gruß Rainer

**Comment by bluerai** [comment]
Correction: not cron but curl

**Comment by bluerai** [comment]
In der gerade hochgeladenen Version des example.js-Scripts ist der Abruf der Daten mit wget (statt curl) im Kommentar eingefügt. Vielleicht klappt's damit.

Gruß bluerai

**Comment by mibr85** [comment]
Hallo @bluerai 
wäre es möglich den Adapter zu übernehmen wenn du ihn nicht mehr weiter pflegen möchtest?
Wo finde ich die Anleitung zum installieren der 0.5.2?
Grüsse Micha

**Comment by bluerai** [comment]
Hallo Micha, 
ja, du kannst den Adapter gerne weiter pflegen. Ich habe dich jetzt erst mal als Contributor eingetragen. Du kannst aber auch einen Fork anlegen.
v0.5.2 wird genauso installiert wie die vorhergehenden. Siehe README.md.
Gruß Rai

**Comment by dg1bor** [comment]
Prima das das Projekt weitergeführt wird.
Werde den Adapter bestimmt auch weiternutzen.

Derzeit nutze ich die Alternative, jedoch bekomme ich meine Window
Kontakte nicht ausgelesen, da es im Beispiel nicht behandelt wurde.


Gruß

Gerhard

Am 06.10.23 um 14:30 schrieb bluerai:

**Comment by mibr85** [comment]
Hallo Gerhard
ich kann leider nix versprechen da ich noch nicht viel erfahrungen mit den adaptern sammeln konnte.
Grüsse

**Comment by jevylux** [comment]
Hallo, habe auch Probleme nit Auslesen von Kontakten.
Habe versucht eine neue id10 hinzu zu fügen

```
const measurement10 =  new Map([
    ["w", {name: "Kontakt", type: "boolean"}], 
    ["ts", {name: "Timestamp", type: "number", unit: "sec"}]
    ["ts", {name: "Timestamp", type: "number", unit: "sec"}]
```
aber ohne Erfolg

**Comment by bluerai** [comment]
Ich denke, so sollte es passen:

const measurement10 =  new Map([
    ["w", {name: "Kontakt", type: "boolean", unit: ""}], 
    ["ts", {name: "Timestamp", type: "number", unit: "sec"}],
    ["lb", {name: "Low Battery", type: "boolean", unit: ""}]]);

Gruß Rai

**Comment by jevylux** [comment]
Danke die Daten werden jetzt ausgelesen. Ich habe aber ein neues Problem. Und zwar scheint es einen Unterschied zwischen der Speicherung der Daten mit dem example.js Script und dem original mobilealerts Adapter. Kann es sein dass `ack: false` im script benutzt wird und nicht im Adapter?

**Comment by bluerai** [comment]
Eigentlich sollte in beiden Fällen ack: false gesetzt sein. Aber was ist konkret das Problem?

**Comment by jevylux** [comment]
Hallo, Danke für das Feedback
Ich benutze den Adapter awtrix-light von Mathias Kleine ( https://github.com/klein0r/ioBroker.awtrix-light )
Ich habe damit vorher Daten vom nobile-alerts Adapter gelesen un alles war ok.
Jetzt will ich dieselben Daten vom example.js ascript einlesen und bekomme keine Daten
Laut Mathias wäre das Problem dass sein Adapter Ack: True verlangt, was mit dem adapter der Fall war

`**Custom apps just display acknowledged values! Control states with `ack: false` are ignored (to prevent duplicate requests and to ensure that values are valid / confirmed)!**`



<img width="315" alt="script" src="https://github.com/bluerai/ioBroker.mobile-alerts/assets/198311/5d21e77a-088b-454f-9ef7-213c5ae42d34">
<img width="359" alt="adapter" src="https://github.com/bluerai/ioBroker.mobile-alerts/assets/198311/87be4d7c-7a72-4070-9721-5361a7448d74">

und hier Auszüge aus dem Log:

beispiel mit daten vom script:
```
awtrix-light.0 | 2023-10-18 10:51:53.950 | debug | [removeApp] Removed customApp app "kummertemp"
-- | -- | -- | --
awtrix-light.0 | 2023-10-18 10:51:53.949 | debug | received 200 response from "/api/custom?name=kummertemp" with content: "OK"
awtrix-light.0 | 2023-10-18 10:51:53.898 | debug | sending "POST" request to "/api/custom?name=kummertemp" without data
awtrix-light.0 | 2023-10-18 10:51:53.897 | debug | [refreshCustomApps] Going to remove custom app "kummertemp" (no state data)
awtrix-light.0 | 2023-10-18 10:51:53.883 | debug | [refreshCustomApps] Refreshing custom app "kummertemp" with icon "55579" and text "Kummer %s %u"
awtrix-light.0 | 2023-10-18 10:51:53.883 | debug | [refreshCustomApps] Refreshing custom apps for objId "javascript.0.mobileAlertsScript.0.Devices.126DC606F634.t1" with data {"type":"number","unit":"°C","ts":1697618792345}

```
Beispiel mit Daten vom Adapter:


```
awtrix-light.0 | 2023-10-18 10:51:55.118 | debug | received 200 response from "/api/custom?name=kummertempadapter" with content: "OK"
-- | -- | -- | --
awtrix-light.0 | 2023-10-18 10:51:55.046 | debug | sending "POST" request to "/api/custom?name=kummertempadapter" with data: {"text":"Kummer Temp Adaptert 21.7","textCase":2,"pos":10,"background":"#000000","color":"#FFFFFF","icon":"55579"}
awtrix-light.0 | 2023-10-18 10:51:54.989 | debug | [refreshCustomApps] Refreshing custom app "kummertempadapter" with icon "55579" and text "Kummer Temp Adaptert %s %u"
awtrix-light.0 | 2023-10-18 10:51:54.989 | debug | [refreshCustomApps] Refreshing custom apps for objId "mobile-alerts.0.126DC606F634.temperature" with data {"val":"21.7","type":"string","ts":1696506447410}
```

**Comment by bluerai** [comment]
ok, der Adapter setzt tatsächlich das ack-Flag. Ich habe das jetzt auch in example.js geändert. Gruß Rai

**Comment by jevylux** [comment]
Danke, aber leider nein
`javascript.0 (10061) script.js.common.mobilealerts compile failed: at script.js.common.mobilealerts:138`

bin leider lein ipobroker/javascript Spezialist, aber diese Zeile funktionniert.

`setState(mobileAlertsPath + "Devices" + "." + item.deviceid + "." + key, {val: item["measurement"][key], ack: true});`

Danke für deinen Support

**Comment by bluerai** [comment]
Danke für die Korrektur: missing "val: " added 
Gruß Rai
