### ISSUE TITLE
Default Wert

### ISSUE THREAD

**Issue by Klugsi80** [bluerai/ioBroker.mobile-alerts#33]
Hi,
Vielen Dank für das Skript!
ich benutze das Measurement04 für die Pooltemperatur (T2). Mein Pool ist eingewintert, somit kommt da aktuell kein Wert.
Könnte man das example Script so erweitern, dass es in dem Fall einen Default Wert liefert? zB "---" oder "0"

ich hätte es damit versucht:

                if (item["measurement"][key].t2 > 0 && item["measurement"][key].t2 < 50)
                {
                    item["measurement"][key].t2 = item["measurement"][key].t2
                }
                else
                {
                    item["measurement"][key].t2 = 0.0
                }
                setState(mobileAlertsPath + "Devices" + "." + item.deviceid + "." + key, {val: item["measurement"][key], ack: true});

aber im Objekt.t2 steht "65295" (bereits vor der Ergänzung des if/else)

**Comment by bluerai** [comment]
Hallo, ich habe die Beispieldatei example.com ergänzt. Neben einigen anderen Anpassungen wird jetzt für die Messwerte 65295 (=kein Sensor gefunden, siehe API-Doku) und 43530 (= Wert außerhalb des Messbereichs, siehe API-Doku) als Voreinstellung null eingesetzt.
Ich hoffe, das hilft dir. Da der Datenpunkt als Zahl definiert wurde kann dort nicht ein String wie "---" eingesetzt werden. 0.0 als Voreinstellung ist ebenfalls nicht so gut, da dieser Wert auch mal ein tatsächlicher Messwert sein kann. Gruß Rai

**Comment by Klugsi80** [comment]
Super, Danke für die schnelle Antwort!!
ja hab auch überlegt was ein vernünftiger Default Wert sein könnte - NULL ist sicher am Besten.
DANKE!!
