### ISSUE TITLE
examplescript liefert keine Daten mehr

### ISSUE THREAD

**Issue by wschiro** [bluerai/ioBroker.mobile-alerts#34]
Ich hatte das script auf meine Sensoren angepasst und es funktionierte einige Wochen problemlos.
Seit dem 13.1. kriege nun keine aktuellen Daten. Ich lass es in iobroker laufen und im Protokoll steht
requesting all states
requesting all objects
received all states
received all objects

javascript 7.1.6
node.  18.19.0
Nun habe ich den Objektbaum unter userdata gelöscht. Beim Start des Skriptes wird der Objektbaum aber nicht wieder angelegt.
Wo soll ich noch suchen??

**Comment by bluerai** [comment]
Hast du es mit der _ungeänderten_ Datei example.js versucht? Damit sollte es funktionieren. 
Protokoll:
javascript.0
2024-01-21 09:18:26.389	info	script.js.common.Integration.MobileAlertsExample: Mobile Alerts: Data successfully received (#1, max. 0.6 sec).
javascript.0
2024-01-21 09:18:25.828	info	script.js.common.Integration.MobileAlertsExample: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0
2024-01-21 09:18:25.775	info	Start javascript script.js.common.Integration.MobileAlertsExample

Dann noch mal schrittweise deine Änderungen überprüfen....

**Comment by wschiro** [comment]
Es liegt nicht absolut am script, ich hatte es auf meine Sensoren angepasst und es lief.
Und nun habe ich es einfach mal auf einen anderen raspi 1:1 portiert und es läuft!
Da ist aber node 16.19.1 drauf. Und das ist mein produktives System, deswegen ändere ich da nichts. Meine Erfahrungen sind eher "never touch a running system". Deswegen teste ich erstmal auf einem 2. raspi. Ob ich am 13.1.  ein upgrade gemacht habe, weiss ich nicht mehr, die log ist nicht mehr da.
Der mobil-alerts Adapter läuft auch problemlos auf 16.19.1 , auf 18.19 auch nicht (JS-controller stopped)
 Ich hab alles auf debug gestellt in der Hoffnung , das die log Hinweise gibt. Hat aber nicht.
Irgendwann kommt ja mal die Zeit, dass man upgrade muss, und darauf will vorbereitet sein.
Ich werde nun eine 2. Instanz von js installieren und dann testen, ich berichte dann.

**Comment by wschiro** [comment]
Also mit 2. Instanz kommt alles doppelt. 0. Instanz von js deaktiviert, Protokoll wie gehabt, all states received, all objects received. iob restart  hat auch nichts gebracht. reboot des Systems auch nicht. Andere Adapter laufen aber, keine Fehlermeldung. Die 18.19 habe ich mit iob nodejs-update installiert.

**Comment by bluerai** [comment]
Also bei mir läift das Example-Script unter node.js 18.17 einwandfrei - Beispiel-Objekte korrekt erzeugt und gefüllt:

Protokoll:
11:13:42.650	info	javascript.0 (12035) Start javascript script.js.common.Integration.MobileAlertsExample
11:13:42.710	info	javascript.0 (12035) script.js.common.Integration.MobileAlertsExample: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
11:13:44.413	info	javascript.0 (12035) script.js.common.Integration.MobileAlertsExample: Mobile Alerts: Data successfully received (#1, max. 1.7 sec).
11:14:46.140	info	javascript.0 (12035) script.js.common.Integration.MobileAlertsExample: Mobile Alerts: Data successfully received (#2, max. 4.1 sec).
11:21:43.344	info	javascript.0 (12035) script.js.common.Integration.MobileAlertsExample: Mobile Alerts: Data successfully received (#3, max. 1.3 sec).
11:28:42.951	info	javascript.0 (12035) script.js.common.Integration.MobileAlertsExample: Mobile Alerts: Data successfully received (#4, max. 0.9 sec).
11:35:43.532	info	javascript.0 (12035) script.js.common.Integration.MobileAlertsExample: Mobile Alerts: Data successfully received (#5, max. 1.5 sec).

Welche Protokollausgaben erhältst du denn?

**Comment by wschiro** [comment]
![image](https://github.com/bluerai/ioBroker.mobile-alerts/assets/79442440/295dbff4-2db8-4a3d-b161-9eca610ae234)
<img width="1164" alt="Bildschirmfoto 2024-01-21 um 12 57 11" src="https://github.com/bluerai/ioBroker.mobile-alerts/assets/79442440/64369b68-fe30-4e15-b18a-b9411bdb60a9">

**Comment by wschiro** [comment]
sorry 2y dasselbe

**Comment by wschiro** [comment]
und unter 16 sieht es anders aus:
<img width="1147" alt="Bildschirmfoto 2024-01-21 um 13 04 20" src="https://github.com/bluerai/ioBroker.mobile-alerts/assets/79442440/f7f6e099-73f0-4009-a4cc-5dd5eb586f1b">
(manche Protokolleinträge kommen 4-fach, ist aber schon ewig so, krieg ich nicht weg

**Comment by bluerai** [comment]
Unter node.js 18 (javascript.1) sehe ich nicht, dass das example-script gestartet wurde. Am besten mal direkt neustarten im Javascript-Fenster. Da drunter siehst du dann Protokoll-Einträge - und zwar nur die vom example-Script.
Schau sie dir an und vielleicht erkennst du schon etwas - ansonsten kannst du sie mir gern mal zusenden...

**Comment by wschiro** [comment]
Also ich habe den js-adapter in der Konsole gelöscht, Diagnose rüberlaufen lassen, restart und dann mit der Graf. Oberfläche den js-adapter neu installiert. Merkwürdiger Weise waren alle scripte js und blockly sofort wieder da und ----
läuft
danke

**Comment by wschiro** [comment]
Ergänzung: die Protokolleinträge haben sich nicht geändert, also sind anders als in der 16

**Comment by wschiro** [comment]
der javascriptadapter funktioniert nicht. hab schon gefixt, neu installiert, nichts hat bisher geholfen
wenn ich die Instanz starte, laufen sofort im Hintergrund scripte, auf die ich keinen Zugriff bekomme

**Comment by wschiro** [comment]
2. Instanz hilft auch nicht, dann sind beide rot auch beim einfachsten script
Hab schon nach deinstallation die javascript nodemodules gelöscht, auch die scriptbackups aber trotzdem sind die alten scripte immer wieder da

**Comment by wschiro** [comment]
Es war der javascriptadapter, habs nun endlich sauber
