### ISSUE TITLE
javascript Datenpunkt ack=true

### ISSUE THREAD

**Issue by marcoschmidt79** [bluerai/ioBroker.mobile-alerts#35]
Die Datenpunkte werden korrekt geschrieben, nur mit Status Ack=false. Da ich die werte gerne weiterverarbeiten möchte und mein Adapter true benötigt, wie bekomme ich den Adapter dazu, Ack=true zu setzen?

**Comment by bluerai** [comment]
Hast du die letzte Version? Also ggf. updaten. Danach sollten die Werte mit { ack : true } gesetzt werden.
Wenn nicht, dann noch mal alle setState-Befehle und setObject-Befehle in main.js überprüfen und ggf. anpassen.

**Comment by bluerai** [comment]
Hinweis: Der Adapter wird nicht mehr gepflegt..
Ich empfehle die Benutzung der offiziellen Mobile Alerts API über ein ioBroker-Script. 
Im Verzeichnis "alternative" habe ich ein Javascript-Beispiel für den Zugriff auf die API abgelegt. Erläuterungen dazu bitte der Mobile Alerts API-Doku (von der MA-Website) entnehmen.

**Comment by marcoschmidt79** [comment]
> Hast du die letzte Version? Also ggf. updaten. Danach sollten die Werte mit { ack : true } gesetzt werden. Wenn nicht, dann noch mal alle setState-Befehle und setObject-Befehle in main.js überprüfen und ggf. anpassen.

:-) Ah ja, die neue Version... Nach einer neuen Version zu schauen bin ich natürlich nicht drauf gekommen. Danke :-D
