### ISSUE TITLE
Lässt sich nicht installieren

### ISSUE THREAD

**Issue by thorsten26** [bluerai/ioBroker.mobile-alerts#7]
Habe ich jetzt schon zweimal versucht zu installieren wie angegeben - Iobroker findet den Adapter nicht.
Bei der Installation über IOBroker selbst (von URL) gibt es einen Haufen Fehlermeldungen.
`$ ./iobroker url "https://github.com/bluerai/ioBroker.mobile-alerts.git" --debug
install https://github.com/bluerai/ioBroker.mobile-alerts/tarball/master
npm install https://github.com/bluerai/ioBroker.mobile-alerts/tarball/master --production --save --prefix "/opt/iobroker" (System call)
npm
 WARN deprecated hawk@6.0.2: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm
 WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions `

Letztendlich wird aber danach der Adapter "Mobile Alerts mit der Version 0.0.1 angezeigt.
Auch das Auslesen der Sensoren funktioniert einwandfrei.
Danke an den Entwickler!

**Comment by bluerai** [comment]
No more issues after installation of js-controller2.0 - all needed upgrades are done.
