### ISSUE TITLE
Temperatur Sensor

### ISSUE THREAD

**Issue by JoeCoooool** [bluerai/ioBroker.mobile-alerts#8]
Hallo

Adapter funktioniert soweit ganz gut

Gibt es eine Möglichkeit nur Temperatur Sensoren anzeigen zu lassen?

Sensor wird erkannt aber keine Temperatur ausgegeben wie bei den Temperatur und Feuchte Sensoren

mfg

**Comment by bluerai** [comment]
Hi, bogiboy,
ich benutze selbst auch den Mobile Alerts Temperatursensor MA 10100. Ist das der Sensor, den du benutzt? Sollte eigentlich funktionieren.
Wenn nicht, sende mir bitte einen passenden Ausschnitt aus dem Quelltext der HTML-Seite vom Mobile-Alerts-Server. Bitte ohne deine Phone ID!
Gruß Bluerai

**Comment by JoeCoooool** [comment]
Hallo

Vielen dank für die Antwort

Ich nutze das TFA Weatherhub System von Dostmann. Ist komplett Baugleich mit dem Mobile Alerts System. 

Nun komischerweise wird mir der Wert nachdem ich den Adapter neu installiert habe angezeigt.

mfg

**Comment by bogiboy** [comment]
Das ist der Sender

<div class="panel panel-default">
    <div class="panel-body">
        <div class="sensor">

<div class="sensor-header">
    <h3>
        <a href="/Home/MeasurementDetails?deviceid=021A822389D8&amp;vendorid=aaa6653d-5f7b-4bd2-ab43-3486d8fdb099&amp;appbundle=eu.mobile_alerts.mobilealerts">Aussen</a>
    </h3>
    <div class="sensor-component">
        <h5>ID</h5>
        <h4>021A822389D8</h4>
    </div>
</div>

<div class="nofloat"></div>

    <div class="sensor-component">
        <h5>Zeitpunkt</h5>
        <h4>12.01.2020 20:19:11</h4>
    </div>
    <div class="sensor-component">
        <h5>Temperatur</h5>
        <h4>1,7 C</h4>
    </div>
        </div>
    </div>
</div>

Gesendet von Mail für Windows 10

Von: bluerai
Gesendet: Sonntag, 12. Januar 2020 20:16
An: bluerai/ioBroker.mobile-alerts
Cc: bogiboy; Author
Betreff: Re: [bluerai/ioBroker.mobile-alerts] Temperatur Sensor (#8)

Hi, bogiboy,
ich benutze selbst auch den Mobile Alerts Temperatursensor MA 10100. Ist das der Sensor, den du benutzt? Sollte eigentlich funktionieren.
Wenn nicht, sende mir bitte einen passenden Ausschnitt aus dem Quelltext der HTML-Seite vom Mobile-Alerts-Server. Bitte ohne deine Phone ID!
Gruß Bluerai

**Comment by bluerai** [comment]
Ok, dann funktioniert es jetzt. Ich schließe den Issue1 Grüße!

**Comment by JoeCoooool** [comment]
Eine Sache noch

Minus Temperaturen werden nicht angezeigt? Sensoren bleiben bei 0 stehen

Kann man das noch einbauen?



Am 12. Januar 2020 20:56:19 schrieb bluerai <notifications@github.com>:

**Comment by bluerai** [comment]
Hi, Temperatursensoren zeigen auch Minustemperaturen an. Bitte nochmals überprüfen! Wenn es tatsächlich nicht geht, sende mir wieder den Quelltextauszug. Gruß B.

**Comment by bogiboy** [comment]
<form action="/Home/MeasurementDetails" class="form-inline"
id="MeasurementDetails" method="post" role="form"> <div class="well">
	<input id="deviceid" name="deviceid" type="hidden" value="021A822389D8" />
	<input id="vendorid" name="vendorid" type="hidden"
value="aaa6653d-5f7b-4bd2-ab43-3486d8fdb099" />
	<input id="appbundle" name="appbundle" type="hidden"
value="eu.mobile_alerts.mobilealerts" />
	<input id="fromepoch" name="fromepoch" type="hidden" value="" />
	<input id="toepoch" name="toepoch" type="hidden" value="" />
	<input type="hidden" value="1" />


<div class="form-group"
style="margin-right:20px;margin-top:20px;margin-bottom:20px;">
	<label for="from">Von</label>
	<div class="input-group date" id="fromdatetimepicker">
	<input aria-describedby="fromdatetimepicker" class="form-control"
id="from" name="from" type="text" value="" />
	<span class="input-group-addon">
	<span class="glyphicon glyphicon-calendar"></span>
	</span>
	</div>
	</div>


<div class="form-group"
style="margin-right:20px;margin-top:20px;margin-bottom:20px;">
	<label for="to">Bis</label>
	<div class="input-group date" id="todatetimepicker">
	<input aria-describedby="todatetimepicker" class="form-control" id="to"
name="to" type="text" value="" />
	<span class="input-group-addon">
	<span class="glyphicon glyphicon-calendar"></span>
	</span>
	</div>
	</div>



<div class="form-group"
style="margin-right:20px;margin-top:20px;margin-bottom:20px;">
	<button class="btn btn-default" id="btnprev"><i class="glyphicon
glyphicon-arrow-left"></i></button>

	<div id="areapanel" class="btn-group" role="group" data-toggle="buttons"
aria-label="...">
	<label class="btn btn-default">
	<input data-value="area" id="area1" name="area" type="radio" value="day"
checked> Tag
	</label>
	<label class="btn btn-default">
	<input data-value="area" id="area2" name="area" type="radio" value="week"
> Woche
	</label>
	<label class="btn btn-default">
	<input data-value="area" id="area3" name="area" type="radio" value="month"
> Monat
	</label>
	</div>


<button class="btn btn-default" id="btnnext"><i class="glyphicon
glyphicon-arrow-right"></i></button>
	</div>

	<button class="btn btn-primary" type="submit" name="command"
value="refresh" style="margin-right:20px;"><i class="glyphicon
glyphicon-refresh"></i>&nbsp;Aktualisieren</button>



</div>
	<table class="table table-striped">
	<thead>
	<tr>
	<th class="timestamp">Zeitpunkt</th>
	<th class="measurement">Temperatur</th>
	</tr>
	</thead>
	<tbody>
	<tr>
	<td class="timestamp">13.01.2020 07:14:24</td>
	<td class="measurement">-2,1 C</td>
	</tr>
	<tr>
	<td class="timestamp">13.01.2020 07:07:21</td>
	<td class="measurement">-2,4 C</td>
	</tr>
	<tr>
	<td class="timestamp">13.01.2020 07:00:19</td>
Am 12. Januar 2020 23:24:51 schrieb bluerai <notifications@github.com>:

**Comment by bluerai** [comment]
Hi, bitte beschreib noch einmal das aktuelle Problem mit den Minustemperaturen, so dass ich es bei mir nachvollziehen kann. Bei mir funktioniert die Datenübernahme von einem Temperatursensor im Gefreierschrank einwandfrei. z.B. -18,5 °C ist kein Problem. 
Hinweis: Ein passender Quelltextauszug muss von der Mobile-Alertsseite "Sensor Überblick" / "Überblick für Phone ID 000000000000" sein.
Gruß B.

**Comment by bluerai** [comment]
Ich schließe das jetzt, da kein Response erfolgt ist.
