### ISSUE TITLE
Datensätze ohne Masseinheit

### ISSUE THREAD

**Issue by animatorecmd** [bluerai/ioBroker.mobile-alerts#9]
Hallo,

zuerst vielen Dank für das Modul, es erweitert meine Möglichkeiten enorm.

Ich versuche aber mit den Werten auch zu rechnen, da die Datensätze aber auch die Maßeinheit enthalten ist das rechnen nicht so einfach.
Wäre es möglich das das Modul die Daten als Objekt Zahl speichert im IoBroker?

Vielen Dank.

**Comment by bluerai** [comment]
Hi, in den Einstellungen für die Instanz die Option "Zahlen extrahieren" auswählen. Dann werden die Zahlenwerte ohne Maßeinheiten abgelegt. Löst das dein Problem?

**Comment by animatorecmd** [comment]
Hi,
die Option ist Angewählt. Die Masseinheit wird aber weiterhin im Objekt mit abgelegt.

Wenn es funktioniert löst es genau mein Problem. (Regen pro Stunde errechen) ;-)

Eine Idee was ich noch machen könnte damit die Option übernommen wird?

**Comment by animatorecmd** [comment]
Edit: Nur bei Regen werden die mm mit Abgelegt, sonst sind alle Datensätze ohne Masseinheit.

**Comment by bluerai** [comment]
Ok, die Maßeinheit mm wird noch nicht berücksichtigt - habe keinen Regensensor. Ich gehe davon aus, dass in dem Feld so etwas wie "2 mm" oder "0,5 mm" steht. Stimmt das?
Ich versuche mal den Code entsprechend zu anzupassen und melde mich dann, damit du das testen kannst. Dauert ca. 1-2 Tage.

**Comment by bluerai** [comment]
Hi, der Code ist nun angepasst. Kurze Rückmeldung wäre nett - auch wenn alles ok ist.

**Comment by bluerai** [comment]
Ok, ich schließe den issue.
